<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>TextureSwapper</AssemblyName>
    <Product>Texture Swapper</Product>
    <Version>1.1.8</Version>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>io.wispforest.textureswapper</RootNamespace>
    <GameRoot>E:\Programs\Steam\steamapps\common\REPO</GameRoot>
    <LibDir>.\libs</LibDir>
<!--    <SolutionDir Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)..\</SolutionDir>-->
    <PublishOutputDir>$(MSBuildThisFileDirectory)PublishOutput</PublishOutputDir>
    <AssetsDir>$(MSBuildThisFileDirectory)assets</AssetsDir>
    <NetMagickVersion>14.6.0</NetMagickVersion>
    <NetMagickType>Magick.NET-Q8-x64</NetMagickType>
  </PropertyGroup>
  
  <!-- Global References -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="MonoMod" Version="22.7.31.1" />
    <PackageReference Include="HarmonyX" Version="2.10.2" />
    
    <PackageReference Include="Zehs.REPOLib" Version="2.1.0"  />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" ExcludeAssets="all" />
    
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Fbx">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Autodesk.Fbx.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="FbxBuildTestAssets">
      <HintPath>$(GameRoot)\REPO_Data\Managed\FbxBuildTestAssets.dll</HintPath>
    </Reference>
    <Reference Include="Klattersynth">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Klattersynth.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Security">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="PhotonChat">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonChat.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Utilities">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonUnityNetworking.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.API">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonVoice.API.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonVoice.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.PUN">
      <HintPath>$(GameRoot)\REPO_Data\Managed\PhotonVoice.PUN.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Sirenix.OdinInspector.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization.Config">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Sirenix.Serialization.Config.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Formats.Fbx.Runtime">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.Formats.Fbx.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.InputSystem.ForUI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Antlr3.Runtime">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.VisualScripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Flow">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.VisualScripting.Flow.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.State">
      <HintPath>$(GameRoot)\REPO_Data\Managed\Unity.VisualScripting.State.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(GameRoot)\REPO_Data\Managed\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    
    <PackageReference Include="FFMpegCore" Version="5.2.0"/>
    <PackageReference Include="Instances" Version="3.0.1"/>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.2"/>
    <PackageReference Include="System.Buffers" Version="4.5.1"/>
    <PackageReference Include="System.IO.Pipelines" Version="9.0.2"/>
    <PackageReference Include="System.Memory" Version="4.5.5"/>
    <PackageReference Include="System.Numerics.Vectors" Version="4.4.0"/>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0"/>
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.2"/>
    <PackageReference Include="System.Text.Json" Version="9.0.2"/>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4"/>

    <PackageReference Include="$(NetMagickType)" Version="$(NetMagickVersion)" />
    <Content Include="$(NuGetPackageRoot)\$(NetMagickType.ToLower())\$(NetMagickVersion)\runtimes\win-x64\native\Magick.Native-Q8-x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Magick.Native-Q8-x64.dll</Link>
    </Content>
    <PackageReference Include="Magick.NET.Core" Version="$(NetMagickVersion)" />

    <PackageReference Include="NAudio" Version="2.0.1" />
    <PackageReference Include="NAudio.Asio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Midi" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    
    <Compile Include="obj\Debug\netstandard2.1\MyPluginInfo.cs"/>
    <Reference Include="Endec">
      <HintPath>$(AssetsDir)Endec.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="RunCompressScript" AfterTargets="Build">
    <PropertyGroup>
      <ProjectDir>$(MSBuildThisFileDirectory)\</ProjectDir>
      <RealTargetDir>$(TargetDir)\</RealTargetDir>
    </PropertyGroup>
    <Exec Command="powershell -File &quot;$(MSBuildProjectDirectory)\PublishTask.ps1&quot; -PublishOutputDir &quot;$(PublishOutputDir)&quot; -ProjectDir &quot;$(ProjectDir)&quot; -TargetDir &quot;$(RealTargetDir)&quot; -AssemblyName &quot;$(AssemblyName)&quot; -Version &quot;$(Version)&quot;" />
  </Target>
</Project>
